# .travis.yml
language: node_js
node_js:
  - '8'
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then cd website && yarn test && yarn install; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd website && yarn test && yarn install && GIT_USER="${GH_NAME}" CURRENT_BRANCH="source" yarn run publish-gh-pages; fi