# Welcome to Jekyll!
#

# Site settings
title: HamWAN Memphis Metro
description: |
  High speed amateur data
owner: HamWAN Memphis Metro # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: hello@memhamwan.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://memhamwan.org" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/memhamwan
  github: https://github.com/memhamwan
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/memhamwan
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/
  #flickr:
  instagram: https://instagram.com/memhamwan
  youtube-square: https://www.youtube.com/channel/UCZQwNR-LaBd8MyIs9EWhb9g
  #spotify:
  #stack-overflosw:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
